AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Mappings (uksb-1q9p31idr).

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Amazon EC2 Configuration'
        Parameters:
          - AmiID
    ParameterLabels:
      AmiID:
        default: 'Amazon Machine Image ID'

Parameters:
  EnvironmentType:
    Description: 'Specify the Environment type of the stack.'
    Type: String
    Default: Test
    AllowedValues:
      - Test
      - Dev
      - Prod
    ConstraintDescription: 'Specify either Test, Dev, or Prod.'

  AmiID:
    Type: AWS::EC2::Image::Id
    Description: 'The ID of the AMI.'

Mappings:
  EnvironmentToInstanceType: # Map name
    Test: # Top level key
      InstanceType: t2.micro # Second level key
    Dev:
      InstanceType: t2.nano
    Prod:
      InstanceType: t2.small

Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiID
      InstanceType: !FindInMap
        - EnvironmentToInstanceType # Map Name
        - !Ref EnvironmentType # First Level Key
        - InstanceType # Second Level Key
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref EnvironmentType, webserver ] ]
